#!/bin/bash

set -e

cd $(dirname $0)

echo "Test local build"

if [[ $1 == "bare" ]]; then
    PIPENV_EXEC=""
fi

${PIPENV_EXEC}python setup.py sdist bdist bdist_wheel
set +e
which pandoc 2> /dev/null > /dev/null
if [[ $? == 0 ]]; then
    echo "Updating README.md from README.rst"
    pandoc --from=rst --to=markdown --output=README.md.in README.rst
    cat << EOF > README.md
<!-- [//]: # (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!)
[//]: # (           This file is automatically generated by 'build.sh' if 'pandoc' is installed.   )
[//]: # (                                                                                          )
[//]: # (                                   Edit 'README.rst' instead !                            )
[//]: # (!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!) -->
EOF
    cat README.md.in >> README.md
    rm -f README.md.in
fi

exit 0
