#!/usr/bin/with-contenv bash

umask 022

cd /app

exec \
    s6-setuidgid abc dopplerr \
        --configfile /config/config.json \
        --output-type plain \
        --general-port 8086 \
        --general-no-color \
        --general-basedir / \
        --general-logfile /config/dopplerr.log \
        --general-appdir /app \
        --general-configdir /config \
        --general-frontenddir /frontend
