#!/usr/bin/with-contenv bash

umask 022

cd /app

exec \
    s6-setuidgid abc pipenv run dopplerr \
        --no-color \
        --verbose \
        --basedir / \
        --port 8086 \
        --appdir /app \
        --configdir /config
